<?php
return [
    's1_01' => ['group' => 'Sarcina 1', 'label' => 'S1.01 · Articol', 'title' => 'Clasă publică + constructor pentru articol', 'source' => 'POO_PHP_SARCINA_1/1.php', 'file' => __DIR__ . '/tasks/s1_01.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'articol constructor public vizualizari vechime'],
    's1_02' => ['group' => 'Sarcina 1', 'label' => 'S1.02 · Indicator fracționar', 'title' => 'Fractional pentru rating și engagement', 'source' => 'POO_PHP_SARCINA_1/01_Fractional.php', 'file' => __DIR__ . '/tasks/s1_02.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'fractional rating engagement evaluari comentarii'],
    's1_03' => ['group' => 'Sarcina 1', 'label' => 'S1.03 · Buget editorial', 'title' => 'Bani pentru bugetul editorial', 'source' => 'POO_PHP_SARCINA_1/02_Bani.php', 'file' => __DIR__ . '/tasks/s1_03.php', 'roles' => ['administrator'], 'keywords' => 'bani buget publicat draft arhivat'],
    's1_04' => ['group' => 'Sarcina 1', 'label' => 'S1.04 · Layout trapez', 'title' => 'Trapez pentru blocurile din dashboard', 'source' => 'POO_PHP_SARCINA_1/03_Trapez.php', 'file' => __DIR__ . '/tasks/s1_04.php', 'roles' => ['administrator','redactor'], 'keywords' => 'trapez layout dashboard carduri'],
    's1_05' => ['group' => 'Sarcina 1', 'label' => 'S1.05 · Triunghi KPI', 'title' => 'Triunghi pentru indicatori editoriali', 'source' => 'POO_PHP_SARCINA_1/04_Triunghi.php', 'file' => __DIR__ . '/tasks/s1_05.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'triunghi kpi rating comentarii vizualizari'],
    's1_06' => ['group' => 'Sarcina 1', 'label' => 'S1.06 · Calculator articole', 'title' => 'Calculator pentru volume editoriale', 'source' => 'POO_PHP_SARCINA_1/05_Calculator.php', 'file' => __DIR__ . '/tasks/s1_06.php', 'roles' => ['administrator','redactor'], 'keywords' => 'calculator articole comentarii total diferenta'],
    's1_07' => ['group' => 'Sarcina 1', 'label' => 'S1.07 · Programare publicare', 'title' => 'Desteptător pentru publicarea articolelor', 'source' => 'POO_PHP_SARCINA_1/06_Desteptator.php', 'file' => __DIR__ . '/tasks/s1_07.php', 'roles' => ['administrator','redactor'], 'keywords' => 'desteptator publicare ora minut programare'],
    's1_08' => ['group' => 'Sarcina 1', 'label' => 'S1.08 · Titlu / șiruri', 'title' => 'Calculator de șiruri pentru titlu și categorie', 'source' => 'POO_PHP_SARCINA_1/07_CalculatorSiruri.php', 'file' => __DIR__ . '/tasks/s1_08.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'siruri titlu categorie concatenare uppercase'],
    's1_11' => ['group' => 'Sarcina 1', 'label' => 'S1.11 · Control acces', 'title' => 'Acces pentru administrarea conturilor', 'source' => 'POO_PHP_SARCINA_1/10_Acces.php', 'file' => __DIR__ . '/tasks/s1_11.php', 'roles' => ['administrator'], 'keywords' => 'acces autentificare conturi admin parola'],
    's2_02' => ['group' => 'Sarcina 2', 'label' => 'S2.02 · Portal / secțiune', 'title' => 'Moștenire între portal și secțiuni', 'source' => 'POO_PHP_SARCINA_2/sarcina_02.php', 'file' => __DIR__ . '/tasks/s2_02.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'portal sectiune mostenire categorii'],
    's2_03' => ['group' => 'Sarcina 2', 'label' => 'S2.03 · BD / tabele', 'title' => 'Baze de date și tabele cross-node', 'source' => 'POO_PHP_SARCINA_2/sarcina_03.php', 'file' => __DIR__ . '/tasks/s2_03.php', 'roles' => ['administrator'], 'keywords' => 'bd tabele baze date noduri mysql'],
    's2_05' => ['group' => 'Sarcina 2', 'label' => 'S2.05 · Stocare / mapă', 'title' => 'Flash și mapă de lucru pentru materiale', 'source' => 'POO_PHP_SARCINA_2/sarcina_05.php', 'file' => __DIR__ . '/tasks/s2_05.php', 'roles' => ['administrator','redactor'], 'keywords' => 'flash mapa fisiere stocare backup'],
    's2_07' => ['group' => 'Sarcina 2', 'label' => 'S2.07 · Get / set profil', 'title' => 'Encapsulare pentru profilurile editoriale', 'source' => 'POO_PHP_SARCINA_2/sarcina_07.php', 'file' => __DIR__ . '/tasks/s2_07.php', 'roles' => ['administrator','redactor'], 'keywords' => 'get set profil redactori incapsulare'],
    's2_08' => ['group' => 'Sarcina 2', 'label' => 'S2.08 · Validare profil', 'title' => 'Validare pe atribute private', 'source' => 'POO_PHP_SARCINA_2/sarcina_08.php', 'file' => __DIR__ . '/tasks/s2_08.php', 'roles' => ['administrator','redactor'], 'keywords' => 'validare private varsta profil'],
    's2_09' => ['group' => 'Sarcina 2', 'label' => 'S2.09 · Utilizatori moșteniți', 'title' => 'Utilizator / angajat / student în platformă', 'source' => 'POO_PHP_SARCINA_2/sarcina_09.php', 'file' => __DIR__ . '/tasks/s2_09.php', 'roles' => ['administrator'], 'keywords' => 'utilizator angajat student mostenire'],
    's2_11' => ['group' => 'Sarcina 2', 'label' => 'S2.11 · Sesiune / flash', 'title' => 'Sesiuni și mesaje flash în portal', 'source' => 'POO_PHP_SARCINA_2/sarcina_11.php', 'file' => __DIR__ . '/tasks/s2_11.php', 'roles' => ['administrator','redactor','cititor'], 'keywords' => 'sesiune flash mesaj autentificare']
];
